name: snapshot

on:
    pull_request:
    push:

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
        -
            name: Set up Go
            uses: actions/setup-go@v1
            with:
                go-version: 1.13.x
        -
            name: Prepare Env vars
            id: prepare
            run: |
                echo ::set-output name=build_time::$(date -u +"%Y-%m-%dT%H:%M:%S")
                echo ::set-output name=build_version::$(git describe --tags 2>/dev/null || echo "v0.0.0")
        -
            name: output
            run: |
                echo version: ${{ job.prepare.outputs.build_version }}
                echo time: ${{ job.prepare.outputs.build_time }}
        -
            name: Build using goreleaser
            uses: goreleaser/goreleaser-action@v1
            with:
                version: latest
                args: release --snapshot --rm-dist
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BUILD_VERSION: ${{ job.prepare.outputs.build_version }}
                BUILD_COMMIT: ${{ github.sha }}
                BUILD_TIME: ${{ job.prepare.outputs.build_time }}